backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: images/uploads

collections:
  - name: "pages"
    label: "Site pages"
    files: 
      - name: "home"
        label: "Home page"
        file: "index-shadow.html"
        fields:
          - name: "title"
            label: "Site title"
            widget: "string"
          - name: "image"
            label: "Site image"
            widget: "image"