backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: images/uploads

collections:
  - name: "main"
    label: "Main page"
    file: "index.html"
    fields:
      - name: "title"
        label: "Site title"
        widget: "string"
      - name: "image"
        label: "Site iamge"
        widget: "image"